spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: http://nacos-registry:8848
