spring:
  datasource:
    url: jdbc:mysql://10.10.10.10/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: peiqi666
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost